version: "2"
plugins:
    similar-code:
        enabled: true
        config:
            languages:
                java:
                    mass_threshold: 88
checks:
   method-lines:
      config:
         threshold: 30
   argument-count:
      config:
         threshold: 7

         
         