version: "2"
plugins:
    similar-code:
        config:
           threshold: 100
    identical-code:
       config:
          threshold: 70
checks:
   method-lines:
      config:
         threshold: 30
   argument-count:
      config:
         threshold: 7
